name: Run detect-secrets
description: Run detect-secrets and write file results locally for consuming
inputs:
  github_token:
    description: GITHUB_TOKEN
    default: ${{ github.token }}
  workdir:
    description: "The directory from which to look for and run detect-secrets. Default: '.'"
    default: "."
  detect_secrets_flags:
    description: Flags and args of detect-secrets command. The default is '--all-files --force-use-all-plugins'.
    default: --all-files --force-use-all-plugins
  json_filename:
    description: Optional. writes findings to file named as per arg. The default is 'results.json'.
    default: "results.json"
runs:
  using: docker
  image: Dockerfile
branding:
  icon: shield
  color: green
